export const CUSTOM_EVENTS = {
  TRANSLATION: {
    STOP_SPEECH_TO_TEXT: 'TRANSLATION.STOP_SPEECH_TO_TEXT',
  },
  CALL: {
    MEETING_END: 'CALL.MEETING_END',
    MEETING_START: 'CALL.MEETING_START',
  }
};
