export const ELECTRON_EVENTS = {
    GOOGLE_LOGIN: 'GOOGLE_LOGIN',
    GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
    GET_SCREEN_SOURCE: 'GET_SCREEN_SOURCE',
    SHARE_SCREEN: 'SHARE_SCREEN',
    SHARE_SCREEN_SUCCESS: 'SHARE_SCREEN_SUCCESS',
    STOP_SHARE_SCREEN: 'STOP_SHARE_SCREEN',
};
  