export const ROUTE_NAMES = {
  ROOT: '/',
  TRANSLATION: '/translation',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  SIGN_UP_SUCCESS: '/sign-up-success',
  FORGOT_PASSWORD: '/forgot-password',
  CREATE_ACCOUNT: '/create-account',
  ACCOUNT_SETTINGS: '/account-settings',
  LOGIN_GOOGLE_ELECTRON: '/login-google-electron',
  RESET_PASSWORD_SENDED: '/reset-password-sended',
  ONLINE_CONVERSATION: '/talk',
  ONLINE_CONVERSATION_CREATE: '/online-conversation/create',
  ONLINE_CONVERSATION_SHARE: '/online-conversation/share',
  ONLINE_CONVERSATION_JOIN: '/online-conversation/join',
  ONLINE_CONVERSATION_NOT_FOUND: '/online-conversation/not-found',
  SPACES: '/spaces',
  SPACE_VERIFY: '/space-verify',
  HELPDESK_CONVERSATION: '/help-desk',
  DESKTOP_LOGIN: '/login-google-electron',
  EXTENSION: '/spaces',
  LANDING_PAGE: '/landing',
  SETTINGS: '/settings',
  WIDGET_NOTIFICATION: '/widget-notification',
  STATIONS: '/stations',
  STATIONS_NEW: '/stations/new',
};
