export const LS_LANG_RECENTLY_USED = 'LS_LANG_RECENTLY_USED';
export const MAX_LANG_RECENTLY_USED = 5;
export const ACCEPT_DIFF_RESULT = 'ACCEPT_DIFFERENCE_RESULT';
export const OC_INFO = 'OC_INFO';
export const ROOM_SETTING = 'ROOM_SETTING';
