export enum SCTranslation {
    SWAP_LANGUAGES = "SWAP_LANGUAGES",
    TOGGLE_HISTORY = "TOGGLE_HISTORY",
    TOGGLE_PHRASES = "TOGGLE_PHRASES",
    TOGGLE_SPEECH_TO_TEXT = "TOGGLE_SPEECH_TO_TEXT",
}

export enum SCConversation {
    NEW_CONVERSATION = "NEW_CONVERSATION",
    TOGGLE_CONVERSATION_SETTINGS = "TOGGLE_CONVERSATION_SETTINGS",
    SEARCH = "SEARCH",
    SWITCH_TO_ALL_TAB = "SWITCH_TO_ALL_TAB",
    SWITCH_TO_GROUP_TAB = "SWITCH_TO_GROUP_TAB",
    VIEW_PINNED_MESSAGES = "VIEW_PINNED_MESSAGES",
    VIEW_CONVERSATION_INFORMATION = "VIEW_CONVERSATION_INFORMATION",
    SWITCH_INPUT_LANGUAGE = "SWITCH_INPUT_LANGUAGE",
    UPLOAD_FILES = "UPLOAD_FILES",
    START_STOP_SPEECH_TO_TEXT = "START_STOP_SPEECH_TO_TEXT",
    OPEN_EMOJI = "OPEN_EMOJI",
}

export enum SCCall {
    MAXIMIZE_MINIMIZE_CALL = "MAXIMIZE_MINIMIZE_CALL",
    ADD_MEMBERS = "ADD_MEMBERS",
    START_STOP_SCREEN_SHARING = "START_STOP_SCREEN_SHARING",
    TOGGLE_CAMERA = "TOGGLE_CAMERA",
    TOGGLE_MICROPHONE = "TOGGLE_MICROPHONE",
    TEMPORARY_MICROPHONE_TOGGLE = "TEMPORARY_MICROPHONE_TOGGLE",
    TOGGLE_DISCUSSION = "TOGGLE_DISCUSSION",
    SWITCH_TO_GALLERY_VIEW = "SWITCH_TO_GALLERY_VIEW",
    START_STOP_SCREEN_DOODLE = "START_STOP_SCREEN_DOODLE",
    TOGGLE_LIVE_CAPTION = "TOGGLE_LIVE_CAPTION",
}

export const SHORTCUTS: Record<SCConversation | SCTranslation | SCCall, string[]> = {
    [SCConversation.NEW_CONVERSATION]: ['shift', 'n'],
    [SCConversation.TOGGLE_CONVERSATION_SETTINGS]: ['shift', '?'],
    [SCConversation.SEARCH]: ['shift', 'f'],
    [SCConversation.SWITCH_TO_ALL_TAB]: ['shift', 'a'],
    [SCConversation.SWITCH_TO_GROUP_TAB]: ['shift', 'g'],
    [SCConversation.VIEW_PINNED_MESSAGES]: ['shift', 'p'],
    [SCConversation.VIEW_CONVERSATION_INFORMATION]: ['shift', 'i'],
    [SCConversation.SWITCH_INPUT_LANGUAGE]: ['shift', 'l'],
    [SCConversation.UPLOAD_FILES]: ['shift', 'u'],
    [SCConversation.START_STOP_SPEECH_TO_TEXT]: ['shift', ' '],
    [SCConversation.OPEN_EMOJI]: ['shift', ','],

    [SCTranslation.SWAP_LANGUAGES]: ['s'],
    [SCTranslation.TOGGLE_HISTORY]: ['h'],
    [SCTranslation.TOGGLE_PHRASES]: ['p'],
    [SCTranslation.TOGGLE_SPEECH_TO_TEXT]: [' '],    

    [SCCall.MAXIMIZE_MINIMIZE_CALL]: ['shift', 'm'],
    [SCCall.ADD_MEMBERS]: ['a'],
    [SCCall.START_STOP_SCREEN_SHARING]: ['s'],
    [SCCall.TOGGLE_CAMERA]: ['c'],
    [SCCall.TOGGLE_MICROPHONE]: ['m'],
    [SCCall.TEMPORARY_MICROPHONE_TOGGLE]: [' '],
    [SCCall.TOGGLE_DISCUSSION]: ['d'],
    [SCCall.SWITCH_TO_GALLERY_VIEW]: ['g'],
    [SCCall.START_STOP_SCREEN_DOODLE]: ['e'],
    [SCCall.TOGGLE_LIVE_CAPTION]: ['l'],
};
