import type { Metadata } from 'next';
import { NEXT_PUBLIC_NAME } from '@/configs/env.public';
import Tiptap from '@/components/tiptap';

export const metadata: Metadata = {
  title: NEXT_PUBLIC_NAME + ' - Design System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
