export * from './logo';
export * from './triangle';
export * from './loading';
export * from './rectangle';
export * from './copy-img-icon';
export * from './multiple-copy-icon';
export * from './svg-spinners-gooey-balls2';
export * from './qr-code-icon';
export * from './SvgSpinners270RingWithBg';
